// GENERATED by scripts/gen-version.mjs at build time. Do not edit by hand.
export const VERSION = {
  commit: 'a5f2138',
  commitFull: 'a5f2138cd8363c08af091cba89376d3b1b590c51',
  builtAt: '2026-10-02T14:09:46.903Z',
} as const;
