// GENERATED by scripts/gen-version.mjs at build time. Do not edit by hand.
export const VERSION = {
  commit: '36d6209',
  commitFull: '36d62099b17098bbdce94bab0d8281437430876b',
  builtAt: '2026-09-08T07:45:20.895Z',
} as const;
