// GENERATED by scripts/gen-version.mjs at build time. Do not edit by hand.
export const VERSION = {
  commit: 'dcf06b5',
  commitFull: 'dcf06b5a8651bf574093cd90a4f72c8020c9cf93',
  builtAt: '2026-09-17T18:14:07.743Z',
} as const;
