/**
 * Bake a build stamp into the source before tsc compiles it.
 *
 * The cPanel deploy copies the prebuilt `dist` folder onto the server; it never
 * runs git there. So "which build is live?" has to be answered by something baked
 * in at MY build time, not read from a repo that is not on the box. This writes
 * src/version.ts (compiled into dist) from git + the clock, and /health reports it.
 *
 * `builtAt` is the reliable signal HERE: if the live /health builtAt matches the
 * one in the committed dist, that exact build is deployed.
 *
 * `commit` is NOT a deploy answer. It names the tip the build was made from,
 * which is the commit BEFORE the one carrying the build, because this file is
 * written before that commit exists. Reading it as "what is live" understates
 * production by one commit every time. The deploy writes $APIROOT/deployed.json
 * from the server's own checkout (see .cpanel.yml) and /health prefers that;
 * `deployed.source` tells you which of the two you are being shown.
 */
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'version.ts');

const git = (cmd) => {
  try { return execSync(cmd, { cwd: join(here, '..'), stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return ''; }
};

const commit = git('git rev-parse --short HEAD') || 'unknown';
const commitFull = git('git rev-parse HEAD') || 'unknown';
const builtAt = new Date().toISOString();

const body = `// GENERATED by scripts/gen-version.mjs at build time. Do not edit by hand.
export const VERSION = {
  commit: '${commit}',
  commitFull: '${commitFull}',
  builtAt: '${builtAt}',
} as const;
`;
writeFileSync(out, body);
console.log(`version stamp: ${commit} @ ${builtAt}`);
